### ISSUE TITLE
enable syntax highlighting of README codeblocks

### ISSUE THREAD

**Issue by noornee** [defensestation/gobroker#1]
hi, i saw your post on the golang subreddit and i clicked to see what it was all about.
i noticed your README code blocks isn't highlighted so i decided to create an issue.

check here [highligt codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)

i.e
```go
newbroker := broker.NewBroker("127.0.0.1", &broker.EndpointOptions{
	Username: "guest",
	Password: "guest",
	Port:     "5672",
})
```

not 

```
newbroker := broker.NewBroker("127.0.0.1", &broker.EndpointOptions{
	Username: "guest",
	Password: "guest",
	Port:     "5672",
})
```

**Comment by gsingh-ds** [comment]
@noornee Thank you the feedback. fixed
